version: 0.0
os: windows
files:
  - source: \
    destination: C:\Users\Administrator\Desktop\apispocc_react_ecommerce_apis
hooks:
  BeforeInstall:
    - location: \scripts\before_install.ps1
      timeout: 300
  AfterInstall:
    - location: \scripts\after_install.ps1
      timeout: 300